import ToastWrapper from "@/components/ToastWrapper"; // Import client-side component
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import "./theme-config.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout of the application.
 *
 * This component renders the HTML structure, including the head, body, and
 * main content area. It also wraps the content in the Radix UI theme provider
 * and sets up the fonts for the application.
 *
 * @param {{ children: React.ReactNode }} props - The props for the component.
 * @returns {JSX.Element} The root layout of the application.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      {/* The main content area of the application. */}
      <body className={inter.variable}>
        {/* The theme provider for the application. */}
        <Theme appearance="light" accentColor="violet">
          {/* The navigation bar for the application. */}
          <NavBar />
          {/* The main content area of the application. */}
          <main className="max-w-7xl mx-auto">{children}</main>
        </Theme>
        {/* Include ToastWrapper for toasts */}
        <ToastWrapper />
      </body>
    </html>
  );
}
