import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./NavBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout of the application.
 *
 * This component renders the HTML structure, including the head, body, and
 * main content area. It also wraps the content in the Radix UI theme provider
 * and sets up the fonts for the application.
 *
 * @param {{ children: React.ReactNode }} props - The props for the component.
 * @returns {JSX.Element} The root layout of the application.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      {/* The main content area of the application. */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* The theme provider for the application. */}
        <Theme>
          {/* The navigation bar for the application. */}
          <NavBar />
          {/* The main content area of the application. */}
          <main className="max-w-7xl mx-auto">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
